project:
  type: website
  output-dir: docs
  render:
    - index.qmd
                
website:
  title: ""
  search: false  
  
        
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
    
   



